[project]
name = "oura-py"
version = "0.1.2"
description = "A python wrapper for Oura Ring's V2 API."
authors = [{ name = "Collin Smith", email = "collinmsmith22@gmail.com" }]
readme = "README.md"
license = "GPL-3.0-only"
requires-python = ">=3.12"
dependencies = ["requests-oauthlib>=2.0.0", "requests>=2.32.3"]

[project.urls]
GitHub = "https://github.com/col-ms/oura-py"

[project.optional-dependencies]
models = ["pydantic>=2.10"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pylint>=3.3.4",
    "pytest-cov>=6.0.0",
    "pytest>=8.3.4",
    "ngrok>=1.7.0",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.6",
    "pydantic>=2.13.4",
    "ty>=0.0.75",
]

[tool.pyright]
typeCheckingMode = "off"
ignore = ["*"]
